config/routes.rb
Bakery::Application.routes.draw do
  resources :cookies

  resources :cakes

end

app/models/cake.rb
class Cake < ActiveRecord::Base
  validates :name, :eggs, :flour, :sugar, :oil, presence: true

  def recipe_sentence
   return "#{name}, #{eggs} eggs, #{flour} ounces of flour, #{sugar} cups of sugar, #{oil} ounces of oil. #{comments}"
  end
end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  before_action :set_cake, only: [:edit, :update, :destroy]

  # GET /cakes
  # GET /cakes.json
  def index
    @cakes = Cake.all
  end

  # GET /cakes/1
  # GET /cakes/1.json
  def show
    @cake = Cake.find(params[:id])
    @cake.oil = @cake.oil + 5
    @cake.save
  end

  # GET /cakes/new
  def new
    @cake = Cake.new
  end

  # GET /cakes/1/edit
  def edit
  end

  # POST /cakes
  # POST /cakes.json
  def create
    @cake = Cake.new(cake_params)

    respond_to do |format|
      if @cake.save
        format.html { redirect_to @cake, notice: 'Cake was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cake }
      else
        format.html { render action: 'new' }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cakes/1
  # PATCH/PUT /cakes/1.json
  def update
    respond_to do |format|
      if @cake.update(cake_params)
        format.html { redirect_to @cake, notice: 'Cake was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cakes/1
  # DELETE /cakes/1.json
  def destroy
    @cake.destroy
    respond_to do |format|
      format.html { redirect_to cakes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cake
      @cake = Cake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cake_params
      params.require(:cake).permit(:name, :eggs, :flour, :sugar, :oil, :comments)
    end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  before_action :set_cooky, only: [:show, :edit, :update, :destroy]

  # GET /cookies
  # GET /cookies.json
  def index
    @cookies = Cookie.all
  end

  # GET /cookies/1
  # GET /cookies/1.json
  def show
  end

  # GET /cookies/new
  def new
    @cooky = Cookie.new
  end

  # GET /cookies/1/edit
  def edit
  end

  # POST /cookies
  # POST /cookies.json
  def create
    @cooky = Cookie.new(cooky_params)

    respond_to do |format|
      if @cooky.save
        format.html { redirect_to @cooky, notice: 'Cookie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cooky }
      else
        format.html { render action: 'new' }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookies/1
  # PATCH/PUT /cookies/1.json
  def update
    respond_to do |format|
      if @cooky.update(cooky_params)
        format.html { redirect_to @cooky, notice: 'Cookie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookies/1
  # DELETE /cookies/1.json
  def destroy
    @cooky.destroy
    respond_to do |format|
      format.html { redirect_to cookies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooky
      @cooky = Cookie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cooky_params
      params.require(:cookie).permit(:name, :eggs, :flour, :sugar, :oil, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cakes/_form.html.erb
<%= form_for(@cake) do |f| %>
  <% if @cake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cake.errors.count, "error") %> prohibited this cake from being saved:</h2>

      <ul>
      <% @cake.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1> Enter your cake recipe here! Thx</h1>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :eggs %><br>
    <%= f.number_field :eggs %>
  </div>
  <div class="field">
    <%= f.label :flour %><br>
    <%= f.number_field :flour %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br>
    <%= f.number_field :sugar %>
  </div>
  <div class="field">
    <%= f.label :oil %><br>
    <%= f.number_field :oil %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cakes/edit.html.erb
<h1>Editing cake</h1>

<%= render 'form' %>

<%= link_to 'Show', @cake %> |
<%= link_to 'Back', cakes_path %>

app/views/cakes/index.html.erb
<h1>Listing cakes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Eggs</th>
      <th>Flour</th>
      <th>Sugar</th>
      <th>Oil</th>
      <th>Comments</th>
      <th>Recipe Sentecne</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cakes.each do |cake| %>
      <tr>
        <td><%= cake.name %></td>
        <td><%= cake.eggs %></td>
        <td><%= cake.flour %></td>
        <td><%= cake.sugar %></td>
        <td><%= cake.oil %></td>
        <td><%= cake.comments %></td>
        <td><%= cake.recipe_sentence %></td>
        <td><%= link_to 'Show', cake %></td>
        <td><%= link_to 'Edit', edit_cake_path(cake) %></td>
        <td><%= link_to 'Destroy', cake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cake', new_cake_path %>

app/views/cakes/new.html.erb
<h1>New cake</h1>

<%= render 'form' %>

<%= link_to 'Back', cakes_path %>

app/views/cakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cake.name %>
</p>

<p>
  <strong>Number of Eggs:</strong>
  <%= @cake.eggs %>
</p>

<p>
  <strong>Ounces of Flour:</strong>
  <%= @cake.flour %>
</p>

<p>
  <strong>Cups of Sugar:</strong>
  <%= @cake.sugar %>
</p>

<p>
  <strong>Ounces of Oil:</strong>
  <%= @cake.oil %>
</p>

<p>
  <strong>Additional Comments:</strong>
  <%= @cake.comments %>
</p>

<p>
  <strong>Full Recipe:</strong>
  <%= @cake.recipe_sentence %>
</p>

<%= link_to 'Edit', edit_cake_path(@cake) %> |
<%= link_to 'Back', cakes_path %>

app/views/cookies/_form.html.erb
<%= form_for(@cooky) do |f| %>
  <% if @cooky.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cooky.errors.count, "error") %> prohibited this cooky from being saved:</h2>

      <ul>
      <% @cooky.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :eggs %><br>
    <%= f.number_field :eggs %>
  </div>
  <div class="field">
    <%= f.label :flour %><br>
    <%= f.number_field :flour %>
  </div>
  <div class="field">
    <%= f.label :sugar %><br>
    <%= f.number_field :sugar %>
  </div>
  <div class="field">
    <%= f.label :oil %><br>
    <%= f.number_field :oil %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookies/edit.html.erb
<h1>Editing cooky</h1>

<%= render 'form' %>

<%= link_to 'Show', @cooky %> |
<%= link_to 'Back', cookies_path %>

app/views/cookies/index.html.erb
<h1>Listing cookies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Eggs</th>
      <th>Flour</th>
      <th>Sugar</th>
      <th>Oil</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cookies.each do |cooky| %>
      <tr>
        <td><%= cooky.name %></td>
        <td><%= cooky.eggs %></td>
        <td><%= cooky.flour %></td>
        <td><%= cooky.sugar %></td>
        <td><%= cooky.oil %></td>
        <td><%= cooky.comments %></td>
        <td><%= link_to 'Show', cooky %></td>
        <td><%= link_to 'Edit', edit_cookie_path(cooky) %></td>
        <td><%= link_to 'Destroy', cooky, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookie', new_cookie_path %>

app/views/cookies/new.html.erb
<h1>New cookie</h1>

<%= render 'form' %>

<%= link_to 'Back', cookies_path %>

app/views/cookies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cooky.name %>
</p>

<p>
  <strong>Eggs:</strong>
  <%= @cooky.eggs %>
</p>

<p>
  <strong>Flour:</strong>
  <%= @cooky.flour %>
</p>

<p>
  <strong>Sugar:</strong>
  <%= @cooky.sugar %>
</p>

<p>
  <strong>Oil:</strong>
  <%= @cooky.oil %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @cooky.comments %>
</p>

<%= link_to 'Edit', edit_cookie_path(@cooky) %> |
<%= link_to 'Back', cookies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bakery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>